name: Sync to Azure DevOps

on:
  push:
    branches:
      - master  # Trigger on push to the 'master' branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add Azure DevOps Remote
        run: |
          # Remove the 'azure' remote if it already exists to avoid conflicts
          git remote remove azure || true
          
          # Add Azure DevOps repository as a remote
          git remote add azure https://$AZURE_DEVOPS_PAT@dev.azure.com/darshanda66/second%20Project/_git/second%20Project
          
          # Verify remotes
          git remote -v

      - name: Push to Azure DevOps
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          # Push the changes to the Azure DevOps repository
          git push azure master:master --force
