name: Sync to Azure DevOps

on:
  push:
    branches:
      - '*'  # Trigger on push to any branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch the full Git history and all branches

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add Azure DevOps Remote
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          # Remove the 'azure' remote if it already exists
          git remote remove azure || true
          
          # Add Azure DevOps repository as a remote using the PAT
          git remote add azure https://$AZURE_DEVOPS_PAT@dev.azure.com/darshanda66/second%20Project/_git/second%20Project
          
          # Verify the remotes
          git remote -v

      - name: Push All Branches to Azure DevOps
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          # Push all branches to Azure DevOps
          git push azure --all --force

      - name: Push Tags to Azure DevOps
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          # Push all tags to Azure DevOps (optional)
          git push azure --tags
